// "use client"; // 👈 مهم جدًا

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PerfumeNavbar from "@/components/layout/Navbar";
import { Footer2 } from "@/components/layout/footer2";
import { CartProvider } from "@/lib/CartContext";
import { Cairo } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cairo = Cairo({
  subsets: ["arabic", "latin"], // ضروري للغة العربية
  weight: ["400", "700"], // الأوزان اللي تحتاجها
  variable: "--font-cairo", // نربطه بـ CSS variable
});

export const metadata = {
  title: "اكليل ابها",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${cairo.variable}  antialiased`}>
        <PerfumeNavbar />
        <div className="bg-neutral-50">
          <CartProvider>{children}</CartProvider>
        </div>
        <Footer2 />
      </body>
    </html>
  );
}
